part of 'resources.dart';

class Images {
  Images._();

  static const String home = 'assets/imgs/Home.png';
  static const String home1 = 'assets/imgs/Home1.png';
  static const String menu = 'assets/imgs/Menu.svg';
  static const String menu2 = 'assets/imgs/Menu2.png';
  static const String qrCode = 'assets/imgs/QR_Code.png';
  static const String shop = 'assets/imgs/Shop.svg';
  static const String shop2 = 'assets/imgs/Shop2.png';
  static const String vector = 'assets/imgs/Vector.svg';
  static const String avatar = 'assets/imgs/avatar.png';
  static const String back = 'assets/imgs/back.png';
  static const String card = 'assets/imgs/card.png';
  static const String cardBack = 'assets/imgs/cardBack.png';
  static const String content1 = 'assets/imgs/content1.png';
  static const String content10 = 'assets/imgs/content10.png';
  static const String content2 = 'assets/imgs/content2.png';
  static const String content3 = 'assets/imgs/content3.png';
  static const String content4 = 'assets/imgs/content4.png';
  static const String content5 = 'assets/imgs/content5.png';
  static const String content6 = 'assets/imgs/content6.png';
  static const String content7 = 'assets/imgs/content7.png';
  static const String content8 = 'assets/imgs/content8.png';
  static const String headphones1 = 'assets/imgs/headphones1.png';
  static const String headphones2 = 'assets/imgs/headphones2.png';
  static const String headphones3 = 'assets/imgs/headphones3.png';
  static const String headphones4 = 'assets/imgs/headphones4.png';
  static const String image36 = 'assets/imgs/image_36.png';
  static const String image50 = 'assets/imgs/image_50.png';
  static const String image51 = 'assets/imgs/image_51.png';
  static const String item = 'assets/imgs/item.png';
  static const String item1 = 'assets/imgs/item1.png';
  static const String item10 = 'assets/imgs/item10.png';
  static const String item11 = 'assets/imgs/item11.png';
  static const String item2 = 'assets/imgs/item2.png';
  static const String item3 = 'assets/imgs/item3.png';
  static const String item4 = 'assets/imgs/item4.png';
  static const String item5 = 'assets/imgs/item5.png';
  static const String item6 = 'assets/imgs/item6.png';
  static const String item7 = 'assets/imgs/item7.png';
  static const String item8 = 'assets/imgs/item8.png';
  static const String item9 = 'assets/imgs/item9.png';
  static const String location = 'assets/imgs/location.png';
  static const String location1 = 'assets/imgs/location1.png';
  static const String location2 = 'assets/imgs/location2.png';
  static const String location3 = 'assets/imgs/location3.png';
  static const String location4 = 'assets/imgs/location4.png';
  static const String location5 = 'assets/imgs/location5.png';
  static const String location6 = 'assets/imgs/location6.png';
  static const String location7 = 'assets/imgs/location7.png';
  static const String location8 = 'assets/imgs/location8.png';
  static const String location9 = 'assets/imgs/location9.png';
  static const String mdiHeart = 'assets/imgs/mdi_heart.svg';
  static const String mdiHeart2 = 'assets/imgs/mdi_heart2.png';
  static const String notification = 'assets/imgs/notification.png';
  static const String product1 = 'assets/imgs/product1.png';
  static const String product2 = 'assets/imgs/product2.png';
  static const String product3 = 'assets/imgs/product3.png';
  static const String product4 = 'assets/imgs/product4.png';
  static const String product5 = 'assets/imgs/product5.png';
  static const String product6 = 'assets/imgs/product6.png';
  static const String scan = 'assets/imgs/scan.png';
  static const String search = 'assets/imgs/search.png';
}
